# App Properties
ims.app.jwtSecret======3453dgdh==ims==uiti787=========================
ims.app.jwtExpirationMs= 86400000
spring.data.mongodb.uri = mongodb://hymoose:rjc2Ryb3syOnAKWelpRdcbdD1FwaFmtsAscluKNlXBGoQINmHG7gv7arCDZu8nJicYoNGxeM7D3oACDbUEZLjw==@hymoose.mongo.cosmos.azure.com:10255/imsdb?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@hymoose@

#location
#catpgory, Name ID, description
